builder:
  track: dev

labels:
  app-group: ziplinee-ci
  type: library
  team: ziplinee
  language: golang

version:
  semver:
    major: 0
    minor: 0
    releaseBranch: main

stages:
  build:
    image: golang:1.17-alpine
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test ./...

  tag-revision:
    image: golang:1.17-alpine
    commands:
    - apk add git
    - git tag v${ZIPLINEE_BUILD_VERSION}
    - git push origin v${ZIPLINEE_BUILD_VERSION}

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: ziplinee
    channels:
    - '#build-status'
    when: status == 'succeeded' || status == 'failed'
